"use client";

import Link from "next/link";
import { useRouter } from "next/navigation";
import { useCallback, useEffect, useRef, useState } from "react";
import { ArrowDown, ArrowLeft, ArrowUp, CalendarClock, Copy, Download, Eye, Plus, Save, Search, Trash2 } from "lucide-react";
import { ARTICLE_TYPES, defaultContent, type Author, type Category, type ContentData, type ContentKind, type ContentRecord, type DocNode, type ListResult, type Role } from "@/lib/types";
import { adminApi, ApiError, dateLabel, errorMessage, friendly, useResource } from "./api";
import { Badge, Card, confirmAction, Field, Loading, Modal, Notice, PageHeading } from "./ui";
import { RichTextEditor } from "./RichTextEditor";
import { scheduledInstant, scheduleLabel } from "./schedule";
import s from "./admin.module.css";

interface Revision { id: string; workflow: string; createdAt: string; data: ContentData }
interface EditorResponse { record: ContentRecord; revisions: Revision[] }
type SaveStatus = "saved" | "unsaved" | "saving" | "error" | "conflict";
const pluralKind = (kind: ContentKind) => kind === "article" ? "articles" : kind === "product" ? "products" : "pages";
const emptyData = () => structuredClone(defaultContent);

function extractProductIds(document: DocNode): string[] {
  const ids: string[] = [];
  const visit = (node: DocNode) => { if (node.type === "productCard" && typeof node.attrs?.productId === "string") ids.push(node.attrs.productId); if (node.type === "comparisonTable" && Array.isArray(node.attrs?.productIds)) ids.push(...node.attrs.productIds.filter((id): id is string => typeof id === "string")); node.content?.forEach(visit); }; visit(document); return [...new Set(ids)];
}

export function ContentEditor({ id, kind, role = "EDITOR", timezone = "Asia/Karachi" }: { id: string; kind: ContentKind; role?: Role; timezone?: string }) {
  const router = useRouter();
  const [data, setData] = useState<ContentData>(emptyData);
  const [record, setRecord] = useState<ContentRecord | null>(null);
  const [revisions, setRevisions] = useState<Revision[]>([]);
  const [loading, setLoading] = useState(id !== "new");
  const [status, setStatus] = useState<SaveStatus>(id === "new" ? "unsaved" : "saved");
  const [failure, setFailure] = useState(""); const [message, setMessage] = useState(""); const [validation, setValidation] = useState<string[]>([]);
  const [tab, setTab] = useState("write"); const [resetKey, setResetKey] = useState(0); const [busyAction, setBusyAction] = useState("");
  const [scheduleOpen, setScheduleOpen] = useState(false); const [scheduledAt, setScheduledAt] = useState("");
  const scheduleUtc = scheduledInstant(scheduledAt, timezone);
  const [productQuery, setProductQuery] = useState(""); const [relatedQuery, setRelatedQuery] = useState("");
  const dataRef = useRef(data); const recordRef = useRef(record); const savedRef = useRef(JSON.stringify(defaultContent)); const savingRef = useRef(false); const statusRef = useRef(status); const inFlightRef = useRef<Promise<ContentRecord | null> | null>(null);
  const { data: categories } = useResource<{ items: Category[] }>("/api/admin/categories");
  const { data: authors } = useResource<{ items: Author[] }>("/api/admin/authors");
  const { data: tags } = useResource<{ items: { id: string; name: string }[] }>("/api/admin/tags");
  const [products, setProducts] = useState<ListResult<ContentRecord> | null>(null);
  const { data: articles } = useResource<ListResult<ContentRecord>>(`/api/admin/content?kind=article&page=1&q=${encodeURIComponent(relatedQuery)}`);
  const canPublish = ["OWNER", "ADMIN", "EDITOR"].includes(role); const scheduled = record?.workflow === "SCHEDULED"; const canEdit = role !== "ANALYST" && !scheduled;
  const [productCache, setProductCache] = useState<Record<string, ContentRecord>>({});
  useEffect(() => { const controller = new AbortController(); const timer = setTimeout(() => { adminApi<ListResult<ContentRecord>>(`/api/admin/content?kind=product&page=1&q=${encodeURIComponent(productQuery)}`, { signal: controller.signal }).then(result => { setProducts(result); setProductCache(previous => ({ ...previous, ...Object.fromEntries(result.items.map(item => [item.id, item])) })); }).catch(() => {}); }, 250); return () => { clearTimeout(timer); controller.abort(); }; }, [productQuery]);
  function setSaveStatus(value: SaveStatus) { statusRef.current = value; setStatus(value); }
  const adoptRecord = useCallback((next: ContentRecord, reset = true) => { recordRef.current = next; setRecord(next); if (reset) { dataRef.current = next.data; setData(next.data); savedRef.current = JSON.stringify(next.data); setResetKey(previous => previous + 1); } }, []);
  useEffect(() => {
    if (id === "new" || recordRef.current?.id === id) return;
    let active = true;
    setLoading(true);
    adminApi<EditorResponse>(`/api/admin/content/${id}`).then(result => { if (active) { adoptRecord(result.record); setRevisions(result.revisions); setSaveStatus("saved"); } }).catch(error => { if (active) setFailure(errorMessage(error)); }).finally(() => { if (active) setLoading(false); });
    return () => { active = false; };
  }, [id, adoptRecord]);

  const saveDraft = useCallback(async (explicit = false): Promise<ContentRecord | null> => {
    if (savingRef.current) return inFlightRef.current;
    if (recordRef.current?.workflow === "SCHEDULED") return recordRef.current;
    if (!explicit && ["error", "conflict"].includes(statusRef.current)) return null;
    const snapshot = structuredClone(dataRef.current);
    if (explicit && !snapshot.title.trim()) { setFailure("Add a title before saving your draft."); setSaveStatus("error"); return null; }
    if (!snapshot.title.trim() && !recordRef.current) return null;
    const savedRecord = recordRef.current;
    if (savedRecord && JSON.stringify(snapshot) === savedRef.current) return savedRecord;
    savingRef.current = true; setSaveStatus("saving"); setFailure(""); setValidation([]);
    const operation = (async () => {
      try {
        const result = await adminApi<{ record: ContentRecord }>(`/api/admin/content${savedRecord ? `/${savedRecord.id}` : ""}`, { method: savedRecord ? "PATCH" : "POST", body: JSON.stringify(savedRecord ? { data: snapshot, version: savedRecord.version } : { kind, data: snapshot }) });
        const unchangedDuringSave = JSON.stringify(dataRef.current) === JSON.stringify(snapshot);
        recordRef.current = result.record; setRecord(result.record);
        savedRef.current = JSON.stringify(result.record.data);
        if (unchangedDuringSave) { dataRef.current = result.record.data; setData(result.record.data); setSaveStatus("saved"); } else { savedRef.current = JSON.stringify(snapshot); setSaveStatus("unsaved"); }
        if (!savedRecord) { router.replace(`/admin/${pluralKind(kind)}/${result.record.id}`); }
        if (explicit) setMessage("Draft saved. Your published revision is unchanged until you publish.");
        return result.record;
      } catch (error) { setFailure(errorMessage(error)); setSaveStatus(error instanceof ApiError && error.status === 409 ? "conflict" : "error"); if (error instanceof ApiError && Array.isArray(error.details)) setValidation(error.details.map(item => typeof item === "string" ? item : JSON.stringify(item))); return null; }
      finally { savingRef.current = false; inFlightRef.current = null; }
    })();
    inFlightRef.current = operation;
    return operation;
  }, [kind, router]);

  useEffect(() => {
    if (!record || scheduled || loading || ["conflict", "error"].includes(status) || JSON.stringify(data) === savedRef.current) return;
    const timer = setTimeout(() => { void saveDraft(); }, 1500); return () => clearTimeout(timer);
  }, [data, record, loading, scheduled, status, saveDraft]);
  useEffect(() => {
    const hasChanges = () => JSON.stringify(dataRef.current) !== savedRef.current;
    const unload = (event: BeforeUnloadEvent) => { if (hasChanges()) event.preventDefault(); };
    let leaving = false;
    const navigate = (event: MouseEvent) => { const anchor = (event.target as Element)?.closest("a[href]") as HTMLAnchorElement | null; if (!anchor || anchor.target === "_blank" || anchor.hasAttribute("download") || anchor.href === window.location.href || event.ctrlKey || event.metaKey) return; if (leaving) { leaving = false; return; } if (!hasChanges()) return; event.preventDefault(); event.stopPropagation(); void confirmAction({ title: "Leave without saving?", message: "You have unsaved changes in this editor. If you leave now, they will be lost.", confirmLabel: "Leave page", cancelLabel: "Keep editing", tone: "danger" }).then(confirmed => { if (confirmed) { leaving = true; anchor.click(); } }); };
    window.addEventListener("beforeunload", unload); document.addEventListener("click", navigate, true); return () => { window.removeEventListener("beforeunload", unload); document.removeEventListener("click", navigate, true); };
  }, []);
  function update<K extends keyof ContentData>(key: K, value: ContentData[K]) {
    if (!canEdit) return;
    const next = { ...dataRef.current, [key]: value }; dataRef.current = next; setData(next); setMessage(""); if (statusRef.current !== "conflict") setSaveStatus("unsaved");
  }
  function updateDocument(document: DocNode) { const next = { ...dataRef.current, document, productIds: [...new Set([...dataRef.current.productIds, ...extractProductIds(document)])] }; dataRef.current = next; setData(next); if (statusRef.current !== "conflict") setSaveStatus("unsaved"); }
  async function reloadLatest() { if (!recordRef.current || !await confirmAction({ title: "Load the latest revision?", message: "This replaces your unsaved changes with the latest server revision. Download your draft first if you need to keep a copy.", confirmLabel: "Load latest", tone: "danger" })) return; try { const result = await adminApi<EditorResponse>(`/api/admin/content/${recordRef.current.id}`); adoptRecord(result.record); setRevisions(result.revisions); setSaveStatus("saved"); setFailure(""); } catch (e) { setFailure(errorMessage(e)); } }
  function downloadDraft() { const url = URL.createObjectURL(new Blob([JSON.stringify(dataRef.current, null, 2)], { type: "application/json" })); const link = document.createElement("a"); link.href = url; link.download = `${dataRef.current.slug || "unsaved-draft"}.json`; link.click(); URL.revokeObjectURL(url); }
  async function workflow(action: string, extra: Record<string, unknown> = {}) {
    const confirmations: Record<string, Parameters<typeof confirmAction>[0]> = {
      publish: { title: `Publish this ${kind}?`, message: "This reviewed revision will become visible to readers as soon as all publication checks pass.", confirmLabel: "Publish", tone: "publish" },
      restoreRevision: { title: "Restore this revision?", message: "It will become the active draft. Your current draft stays in revision history.", confirmLabel: "Restore revision" },
      unpublish: { title: `Unpublish this ${kind}?`, message: "It will be removed from the live site. You can publish it again later.", confirmLabel: "Unpublish", tone: "danger" },
      archive: { title: `Archive this ${kind}?`, message: "It will be archived and removed from the live site.", confirmLabel: "Archive", tone: "danger" },
      trash: { title: `Move this ${kind} to trash?`, message: "It will be moved to trash and removed from the live site.", confirmLabel: "Move to trash", tone: "danger" },
    };
    if (confirmations[action] && !await confirmAction(confirmations[action])) return;
    setBusyAction(action); setMessage(""); setFailure(""); setValidation([]);
    try {
      const active = action === "cancelSchedule" || action === "restore" ? recordRef.current : await saveDraft(true);
      if (!active) return;
      if (JSON.stringify(dataRef.current) !== savedRef.current) { setFailure("New edits arrived while saving. Save them before changing publication status."); return; }
      const result = await adminApi<{ record: ContentRecord }>(`/api/admin/content/${active.id}`, { method: "POST", body: JSON.stringify({ action, version: active.version, ...extra }) });
      if (action === "duplicate") { router.push(`/admin/${pluralKind(kind)}/${result.record.id}`); return; }
      adoptRecord(result.record); setSaveStatus("saved"); setMessage(`${friendly(action)} completed.`); setScheduleOpen(false);
      const loaded = await adminApi<EditorResponse>(`/api/admin/content/${active.id}`); setRevisions(loaded.revisions);
    } catch (error) { setFailure(errorMessage(error)); if (error instanceof ApiError && error.status === 409) setSaveStatus("conflict"); if (error instanceof ApiError && Array.isArray(error.details)) setValidation(error.details.map(item => typeof item === "string" ? item : JSON.stringify(item))); }
    finally { setBusyAction(""); }
  }
  const texts = (key: keyof ContentData, label: string, hint?: string, multiline = false) => <Field label={label} hint={hint}>{multiline ? <textarea className={s.textarea} disabled={!canEdit} value={String(data[key])} onChange={e => update(key, e.target.value as never)} /> : <input className={s.input} disabled={!canEdit} value={String(data[key])} onChange={e => update(key, e.target.value as never)} />}</Field>;
  if (loading) return <Loading />;
  if (id !== "new" && !record) return <><PageHeading title="Content unavailable" description="This record could not be opened." /><Notice message={failure} error /><Link href={`/admin/${pluralKind(kind)}`} className={s.secondary}>Return to {pluralKind(kind)}</Link></>;
  return <>
    <PageHeading title={record ? `Edit ${kind}` : `Create ${kind}`} description={kind === "product" ? "Document the evidence behind every recommendation." : kind === "page" ? "Pages hold the lasting parts of your site, like About, Privacy policy, or Affiliate disclosure." : "A useful article starts with a clear question and dependable research."}><Link className={s.secondary} href={`/admin/${pluralKind(kind)}`}><ArrowLeft size={14} />All {pluralKind(kind)}</Link><span className={s.saveState} role="status">{status === "saved" ? "All changes saved" : status === "saving" ? "Saving draft…" : status === "conflict" ? "Revision conflict" : status === "error" ? "Save failed" : "Unsaved changes"}</span>{record && <Link href={`/preview/${record.id}`} target="_blank" className={s.secondary}><Eye size={15} />Preview</Link>}<button className={s.button} disabled={!canEdit || status === "saving" || status === "conflict" || !!busyAction} onClick={() => void saveDraft(true)}><Save size={15} />Save draft</button></PageHeading>
    <Notice message={message} /><Notice message={failure} error />{validation.length > 0 && <div className={s.notice} data-error="true"><ul style={{ margin: 0, paddingLeft: 18 }}>{validation.map((issue, index) => <li key={index}>{issue}</li>)}</ul></div>}{status === "conflict" && <div className={s.actionRow} style={{ marginBottom: 20 }}><button className={s.secondary} onClick={downloadDraft}><Download size={14} />Download your draft</button><button className={s.secondary} onClick={() => void reloadLatest()}>Load latest server revision</button></div>}{scheduled && <Notice message="This scheduled revision is locked. Cancel its schedule to make changes, then schedule the updated draft again." />}
    <div className={s.editorLayout}><div><div className={s.tabs} role="tablist" aria-label="Content editor sections">{(kind === "article" ? [{ key: "write", label: "Write" }, { key: "seo", label: "SEO" }, { key: "products", label: "Affiliate products" }, { key: "faqs", label: "FAQs" }] : kind === "page" ? [{ key: "write", label: "Write" }, { key: "seo", label: "SEO" }] : [{ key: "write", label: "Writing" }, { key: "research", label: "Research & sources" }, { key: "seo", label: "Search & sharing" }, { key: "history", label: "Revision history" }]).map(item => <button key={item.key} role="tab" aria-selected={tab === item.key} data-active={tab === item.key} onClick={() => setTab(item.key)}>{item.label}</button>)}</div>
      {tab === "write" && <><Card><input className={`${s.input} ${s.editorTitle}`} aria-label={`${friendly(kind)} title`} placeholder={kind === "product" ? "Product name" : kind === "page" ? "Page title, e.g. About us" : "Give your story a useful title…"} disabled={!canEdit} value={data.title} onChange={e => { const next = e.target.value; update("title", next); if (!record && (!dataRef.current.slug || dataRef.current.slug === data.title.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, ""))) update("slug", next.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "")); }} /><div style={{ marginTop: 18 }}>{texts("slug", "URL slug", kind === "page" ? `This page will live at /${data.slug || "your-slug"}. Changing a published path requires a redirect.` : "Keep the address short and descriptive. Changing a published path requires a redirect.")}{texts("excerpt", "Short introduction", kind === "page" ? "Shown under the page title and in search results." : "A useful summary for article cards, search results, and readers.", true)}</div>{kind === "product" && <><div className={s.fieldGrid}>{texts("brand", "Brand")}{texts("model", "Model")}{texts("asin", "Amazon ASIN", "Identification only; an ASIN does not verify a product claim.")}{texts("amazonUrl", "Approved Amazon.com URL")}</div>{texts("recommendation", "Editorial recommendation", "Explain who this product suits, based on the recorded evidence.", true)}<div className={s.fieldGrid}><Field label="Strengths" hint="One evidence-backed strength per line."><textarea className={s.textarea} disabled={!canEdit} value={data.strengths.join("\n")} onChange={e => update("strengths", e.target.value.split("\n"))} /></Field><Field label="Limitations" hint="One limitation per line."><textarea className={s.textarea} disabled={!canEdit} value={data.limitations.join("\n")} onChange={e => update("limitations", e.target.value.split("\n"))} /></Field></div></>}</Card>
      {kind === "product" && <Card title="Verified specifications" action={<button className={s.secondary} disabled={!canEdit} onClick={() => update("specifications", [...data.specifications, { key: "", value: "", unit: "", sourceUrl: "" }])}><Plus size={13} />Add specification</button>}>{!data.specifications.length && <p className={`${s.small} ${s.muted}`}>Add values you have independently checked, along with the source for each claim.</p>}{data.specifications.map((specification, index) => <div className={s.repeatedRow} key={index}><div className={s.fieldGrid}>{(["key", "value", "unit", "sourceUrl"] as const).map(key => <Field key={key} label={key === "key" ? "Attribute" : key === "sourceUrl" ? "Source URL" : friendly(key)}><input className={s.input} disabled={!canEdit} value={specification[key]} onChange={e => update("specifications", data.specifications.map((item, i) => i === index ? { ...item, [key]: e.target.value } : item))} /></Field>)}</div><button className={s.secondary} disabled={!canEdit} onClick={() => update("specifications", data.specifications.filter((_, i) => i !== index))}><Trash2 size={13} />Remove</button></div>)}</Card>}
      <Card title={kind === "product" ? "Editorial product notes" : kind === "page" ? "Page content" : "The story"} body={false}><RichTextEditor value={data.document} onChange={updateDocument} resetKey={resetKey} disabled={!canEdit} products={Object.values(productCache)} /></Card>
      <Card title="Featured image">{texts("image", "Image URL", "Copy an approved image URL from the Media library.")}<div className={s.fieldGrid}>{texts("imageAlt", "Alternative text")}{texts("imageCredit", "Image credit")}</div><Link href="/admin/media" target="_blank" className={s.secondary}>Open media library ↗</Link></Card>
      </>}
      {tab === "products" && kind === "article" && <Card title="Affiliate products"><p className={`${s.small} ${s.muted}`} style={{ marginTop: 0 }}>Selected products appear as cards at the end of the article, in this order. Only published products can be used. To place a product inside the text, use Editorial blocks → Product recommendation in the Write tab.</p><div className={s.search} style={{ marginBottom: 14 }}><Search size={16} /><input className={s.input} aria-label="Search product references" placeholder="Search your product library…" value={productQuery} onChange={e => setProductQuery(e.target.value)} /></div><div className={s.pickList}>{products?.items.length ? products.items.map(product => <label key={product.id} className={s.check}><input type="checkbox" disabled={!canEdit} checked={data.productIds.includes(product.id)} onChange={e => update("productIds", e.target.checked ? [...data.productIds, product.id] : data.productIds.filter(value => value !== product.id))} />{product.data.title}<Badge value={product.state} /></label>) : <p className={`${s.small} ${s.muted}`}>No matching products. Add a product to your library first.</p>}</div>{data.productIds.map((productId, index) => <div className={s.sortRow} key={productId} draggable={canEdit} onDragStart={e => e.dataTransfer.setData("text/plain", String(index))} onDragOver={e => e.preventDefault()} onDrop={e => { e.preventDefault(); const from = Number(e.dataTransfer.getData("text/plain")); if (!Number.isInteger(from) || from < 0 || from >= data.productIds.length) return; const items = [...data.productIds]; const [moved] = items.splice(from, 1); items.splice(index, 0, moved); update("productIds", items); }} style={{ marginTop: 10 }}><span className={s.small} style={{ flex: 1 }}>{index + 1}. {productCache[productId]?.data.title || productId}</span><button className={s.iconButton} disabled={!canEdit || index === 0} aria-label="Move product up" onClick={() => { const items = [...data.productIds]; [items[index - 1], items[index]] = [items[index], items[index - 1]]; update("productIds", items); }}><ArrowUp size={14} /></button><button className={s.iconButton} disabled={!canEdit || index === data.productIds.length - 1} aria-label="Move product down" onClick={() => { const items = [...data.productIds]; [items[index + 1], items[index]] = [items[index], items[index + 1]]; update("productIds", items); }}><ArrowDown size={14} /></button><button className={s.iconButton} disabled={!canEdit} aria-label="Remove product reference" onClick={() => update("productIds", data.productIds.filter(value => value !== productId))}><Trash2 size={14} /></button></div>)}</Card>}
      {tab === "write" && kind === "article" && <Card title="Related reading"><div className={s.search} style={{ marginBottom: 14 }}><Search size={16} /><input className={s.input} aria-label="Search related articles" placeholder="Search related articles…" value={relatedQuery} onChange={e => setRelatedQuery(e.target.value)} /></div><div className={s.pickList}>{articles?.items.filter(article => article.id !== record?.id).map(article => <label key={article.id} className={s.check}><input type="checkbox" disabled={!canEdit} checked={data.relatedIds.includes(article.id)} onChange={e => update("relatedIds", e.target.checked ? [...data.relatedIds, article.id] : data.relatedIds.filter(value => value !== article.id))} />{article.data.title}</label>)}</div></Card>}
      {tab === "faqs" && kind === "article" && <Card title="Frequently asked questions" action={<button className={s.secondary} disabled={!canEdit || data.faqs.length >= 30} onClick={() => update("faqs", [...data.faqs, { question: "", answer: "" }])}><Plus size={14} />Add FAQ</button>}>{!data.faqs.length && <p className={`${s.small} ${s.muted}`}>Add the questions readers ask most. FAQs appear near the end of the article.</p>}{data.faqs.map((faq, index) => <div className={s.repeatedRow} key={index}><div className={s.rowHeader}><strong>FAQ {index + 1}</strong><button className={s.iconButton} disabled={!canEdit} aria-label={`Remove FAQ ${index + 1}`} onClick={() => update("faqs", data.faqs.filter((_, i) => i !== index))}><Trash2 size={15} /></button></div><Field label="Question"><input className={s.input} disabled={!canEdit} maxLength={300} value={faq.question} onChange={e => update("faqs", data.faqs.map((item, i) => i === index ? { ...item, question: e.target.value } : item))} /></Field><Field label="Answer"><textarea className={s.textarea} disabled={!canEdit} maxLength={3000} value={faq.answer} onChange={e => update("faqs", data.faqs.map((item, i) => i === index ? { ...item, answer: e.target.value } : item))} /></Field></div>)}</Card>}
      {tab === "research" && <><Card title="Research basis">{texts("researchBasis", "How this content was researched", "Describe your actual research method. Clearly distinguish desk research from hands-on testing.", true)}<Field label="Next editorial review"><input type="date" className={s.input} disabled={!canEdit} value={data.reviewDueAt.slice(0, 10)} onChange={e => update("reviewDueAt", e.target.value)} /></Field><label className={s.check}><input type="checkbox" disabled={!canEdit} checked={data.ownerReviewed} onChange={e => update("ownerReviewed", e.target.checked)} />The owner has reviewed factual claims and publication details</label></Card><Card title="Source references" action={<button className={s.secondary} disabled={!canEdit} onClick={() => update("sources", [...data.sources, { title: "", url: "", note: "", verifiedAt: new Date().toISOString().slice(0, 10) }])}><Plus size={14} />Add source</button>}>{!data.sources.length && <p className={`${s.small} ${s.muted}`}>Record primary sources for your product, specification, and safety claims.</p>}{data.sources.map((source, index) => <div className={s.repeatedRow} key={index}><div className={s.rowHeader}><strong>Source {index + 1}</strong><button className={s.iconButton} disabled={!canEdit} aria-label={`Remove source ${index + 1}`} onClick={() => update("sources", data.sources.filter((_, i) => i !== index))}><Trash2 size={15} /></button></div>{(["title", "url", "note", "verifiedAt"] as const).map(key => <Field key={key} label={key === "verifiedAt" ? "Last verified" : key === "url" ? "Source URL" : key === "note" ? "What this source supports" : "Source title"}><input type={key === "verifiedAt" ? "date" : "text"} disabled={!canEdit} className={s.input} value={key === "verifiedAt" ? source[key].slice(0, 10) : source[key] || ""} onChange={e => update("sources", data.sources.map((item, i) => i === index ? { ...item, [key]: e.target.value } : item))} /></Field>)}</div>)}</Card></>}
      {tab === "seo" && <><Card title="Search appearance">{texts("seoTitle", "Search title", `${data.seoTitle.length} characters. Around 50–60 characters is useful guidance, not a publication rule.`)}{texts("seoDescription", "Search description", `${data.seoDescription.length} characters. Write a clear, specific summary for readers.`, true)}<label className={s.check}><input type="checkbox" disabled={!canEdit} checked={data.noindex} onChange={e => update("noindex", e.target.checked)} />Ask search engines not to index this content</label><p className={`${s.small} ${s.muted}`}>Drafts are always private. Publication and production indexing settings are checked separately.</p></Card><Card title="Search preview"><div className={s.searchPreview}><small>powerplugpicks.com › {kind === "article" ? "guides › " : kind === "page" ? "" : `${pluralKind(kind)} › `}{data.slug || "your-slug"}</small><strong>{data.seoTitle || data.title || "Your page title"}</strong><p>{data.seoDescription || data.excerpt || "Your clear, helpful description will appear here."}</p></div><p className={`${s.small} ${s.muted}`}>Search engines may choose different titles and descriptions. The featured image is used for social sharing.</p></Card></>}
      {tab === "history" && <Card title="Revision history">{revisions.length ? <ul className={s.list}>{revisions.map(revision => <li key={revision.id}><div className={s.rowHeader}><div><strong className={s.small}>{revision.data.title || "Untitled draft"}</strong><span className={s.tableSubtitle}>{dateLabel(revision.createdAt)} · {new Date(revision.createdAt).toLocaleTimeString()} · {revision.id.slice(0, 8)}</span></div><Badge value={revision.workflow} /></div><button className={s.secondary} disabled={!canEdit || !!busyAction || revision.id === record?.revisionId} onClick={() => void workflow("restoreRevision", { revisionId: revision.id })}>Restore as draft</button></li>)}</ul> : <p className={`${s.small} ${s.muted}`}>Saved revisions will appear here after your first save. The current published revision remains live until you publish an update.</p>}</Card>}
    </div><aside className={s.editorSide}><Card title="Publication"><div className={s.splitLine}><span className={s.muted}>Workflow</span><Badge value={record?.workflow || "DRAFT"} /></div><div className={s.splitLine}><span className={s.muted}>Reader visibility</span><Badge value={record?.state || "UNPUBLISHED"} /></div>{record?.publishedAt && <div className={s.splitLine}><span className={s.muted}>Published</span><span>{dateLabel(record.publishedAt)}</span></div>}<div className={s.actionRow} style={{ marginTop: 18 }}>{scheduled ? <button className={`${s.secondary} ${s.fullWidth}`} disabled={!!busyAction} onClick={() => void workflow("cancelSchedule")}>Cancel schedule to edit</button> : <>{canPublish && <><button className={`${s.button} ${s.fullWidth}`} disabled={!!busyAction || status === "conflict"} onClick={() => void workflow("publish")}>{busyAction === "publish" ? "Checking publication…" : record?.state === "PUBLISHED" ? "Publish updated revision" : "Publish content"}</button><button className={`${s.secondary} ${s.fullWidth}`} disabled={!!busyAction} onClick={() => setScheduleOpen(true)}><CalendarClock size={15} />Schedule publication</button></>}<button className={`${s.secondary} ${s.fullWidth}`} disabled={!!busyAction} onClick={() => void workflow("review")}>Submit for review</button>{canPublish && <button className={`${s.secondary} ${s.fullWidth}`} disabled={!!busyAction} onClick={() => void workflow("approve")}>Mark approved</button>}</>}</div><p className={`${s.small} ${s.muted}`}>{kind === "page" ? "Publishing checks the title, address, introduction, and page content." : "Publishing checks your sources, references, metadata, and editorial requirements."}</p></Card>
      {kind !== "page" && <Card title="Organization">{kind === "article" && <Field label="Article type"><select className={`${s.select} ${s.fullWidth}`} disabled={!canEdit} value={data.articleType} onChange={e => update("articleType", e.target.value as ContentData["articleType"])}>{ARTICLE_TYPES.map(type => <option key={type} value={type}>{friendly(type)}</option>)}</select></Field>}<Field label="Primary category"><select className={`${s.select} ${s.fullWidth}`} disabled={!canEdit} value={data.categoryIds[0] || ""} onChange={e => update("categoryIds", e.target.value ? [e.target.value, ...data.categoryIds.filter(value => value !== e.target.value)] : [])}><option value="">Choose a category…</option>{categories?.items.map(category => <option key={category.id} value={category.id}>{category.name}</option>)}</select></Field><details className={s.small}><summary>Additional categories</summary><div className={s.pickList} style={{ marginTop: 10 }}>{categories?.items.filter(category => category.id !== data.categoryIds[0]).map(category => <label className={s.check} key={category.id}><input type="checkbox" disabled={!canEdit || !data.categoryIds.length} checked={data.categoryIds.includes(category.id)} onChange={e => update("categoryIds", e.target.checked ? [...data.categoryIds, category.id] : data.categoryIds.filter(value => value !== category.id))} />{category.name}</label>)}</div></details>{kind === "article" && <><div style={{ marginTop: 16 }}><Field label="Public author"><select className={`${s.select} ${s.fullWidth}`} disabled={!canEdit} value={data.authorId} onChange={e => update("authorId", e.target.value)}><option value="">Choose an author…</option>{authors?.items.map(author => <option key={author.id} value={author.id}>{author.name}</option>)}</select></Field></div><details className={s.small}><summary>Tags ({data.tagIds.length})</summary><div className={s.pickList} style={{ marginTop: 10 }}>{tags?.items.map(tag => <label className={s.check} key={tag.id}><input type="checkbox" disabled={!canEdit} checked={data.tagIds.includes(tag.id)} onChange={e => update("tagIds", e.target.checked ? [...data.tagIds, tag.id] : data.tagIds.filter(value => value !== tag.id))} />{tag.name}</label>)}</div></details></>}<label className={s.check} style={{ marginTop: 15 }}><input type="checkbox" disabled={!canEdit} checked={data.featured} onChange={e => update("featured", e.target.checked)} />Feature on homepage</label></Card>}
      {record && <Card title="Content actions"><div className={s.actionRow}><button className={`${s.secondary} ${s.fullWidth}`} disabled={!!busyAction || scheduled} onClick={() => void workflow("duplicate")}><Copy size={14} />Duplicate as draft</button>{canPublish && record.state === "PUBLISHED" && <button className={`${s.secondary} ${s.fullWidth}`} disabled={!!busyAction} onClick={() => void workflow("unpublish")}>Unpublish</button>}{record.state === "TRASHED" || record.state === "ARCHIVED" ? <button className={`${s.secondary} ${s.fullWidth}`} disabled={!!busyAction} onClick={() => void workflow("restore")}>Restore to draft</button> : <>{canPublish && <button className={`${s.secondary} ${s.fullWidth}`} disabled={!!busyAction || scheduled} onClick={() => void workflow("archive")}>Archive</button>}<button className={`${s.danger} ${s.fullWidth}`} disabled={!!busyAction || scheduled} onClick={() => void workflow("trash")}><Trash2 size={14} />Move to trash</button></>}</div><p className={`${s.small} ${s.muted}`}>Trashed content can be restored. Referenced records are protected by server checks.</p></Card>}
    </aside></div>
    {scheduleOpen && <Modal title="Schedule publication" close={() => setScheduleOpen(false)} footer={<><button className={s.secondary} onClick={() => setScheduleOpen(false)}>Cancel</button><button className={s.button} disabled={!scheduleUtc || !!busyAction} onClick={() => { if (!scheduleUtc || new Date(scheduleUtc).getTime() <= Date.now()) { setFailure("Choose a future publication time."); return; } void workflow("schedule", { scheduledAt: scheduleUtc }); }}>{busyAction ? "Scheduling…" : "Confirm schedule"}</button></>}><Field label="Publication date and time" hint={`Your publication’s timezone: ${timezone}.`}><input className={s.input} type="datetime-local" value={scheduledAt} onChange={e => setScheduledAt(e.target.value)} /></Field>{scheduleUtc && <Notice message={`Scheduled for ${scheduleLabel(scheduleUtc, timezone)}. Stored in UTC: ${scheduleUtc}.`} />}{scheduledAt && !scheduleUtc && <Notice message="This local time is not valid in your publication’s timezone. Choose another time." error />}<p className={`${s.small} ${s.muted}`}>Publication checks run before scheduling. This revision will be locked until the schedule is cancelled or published.</p></Modal>}
  </>;
}

