"use client";

import Link from "next/link";
import { useState } from "react";
import { BookOpen, Download, ExternalLink, FileCheck2, LockKeyhole, Plus, RefreshCw, Search, ShieldCheck, Trash2, Users } from "lucide-react";
import { adminApi, dateLabel, errorMessage, friendly, useResource } from "./api";
import { Badge, Card, confirmAction, Empty, Field, Loading, Notice, PageHeading } from "./ui";
import s from "./admin.module.css";
import { InvitationForm } from "./InvitationForm";

interface AnalyticsData { pageViews: number; affiliateClicks: number; daily: { date: string; pageViews: number; affiliateClicks: number }[]; topPages: { path: string; views: number; clicks: number }[] }
export function Analytics() {
  const [days, setDays] = useState("30");
  const { data, error, loading } = useResource<AnalyticsData>(`/api/admin/analytics?days=${days}`);
  return <><PageHeading title="Reader analytics" description="Understand how readers find your content and explore recommendations."><select className={s.select} value={days} onChange={e => setDays(e.target.value)} aria-label="Analytics period"><option value="7">Last 7 days</option><option value="30">Last 30 days</option><option value="90">Last 90 days</option></select></PageHeading><Notice message={error} error />{loading ? <Loading /> : data && <><div className={s.grid} style={{ gridTemplateColumns: "repeat(2,minmax(0,1fr))" }}><div className={s.stat}><span className={s.muted}>Collected page views</span><strong>{data.pageViews.toLocaleString()}</strong><small>Reader requests with analytics enabled</small></div><div className={s.stat}><span className={s.muted}>Affiliate link clicks</span><strong>{data.affiliateClicks.toLocaleString()}</strong><small>Outbound product clicks, not purchases</small></div></div><Card title="Page views over time">{data.daily.some(day => day.pageViews > 0) ? <><div className={s.chart} role="img" aria-label={`Daily page views over the last ${days} days`}>{data.daily.map(day => <div key={day.date} className={s.bar} style={{ height: `${Math.max(1, day.pageViews / Math.max(...data.daily.map(row => row.pageViews), 1) * 100)}%` }} title={`${day.date}: ${day.pageViews} page views, ${day.affiliateClicks} affiliate clicks`} />)}</div><div className={s.splitLine}><span>{dateLabel(data.daily[0]?.date)}</span><span>{dateLabel(data.daily.at(-1)?.date)}</span></div><details className={s.small}><summary>View daily data</summary><div className={s.tableWrap}><table className={s.table}><thead><tr><th>Date</th><th>Page views</th><th>Affiliate clicks</th></tr></thead><tbody>{data.daily.map(day => <tr key={day.date}><td>{dateLabel(day.date)}</td><td>{day.pageViews}</td><td>{day.affiliateClicks}</td></tr>)}</tbody></table></div></details></> : <Empty title="Waiting for your first readers" description="Actual collected traffic will appear here once analytics is enabled and readers visit your published content." />}</Card><Card title="Content performance" body={false}>{data.topPages.length ? <div className={s.tableWrap}><table className={s.table}><thead><tr><th>Page</th><th>Views</th><th>Affiliate clicks</th></tr></thead><tbody>{data.topPages.map(page => <tr key={page.path}><td>{page.path}</td><td>{page.views.toLocaleString()}</td><td>{page.clicks.toLocaleString()}</td></tr>)}</tbody></table></div> : <Empty title="No page activity yet" description="Your most visited pages will be listed here when data is available." />}</Card></>}</>;
}

interface SeoData { findings: { severity: string; title: string; detail: string; href: string }[]; redirects: { id: string; source: string; target: string }[] }
export function SeoManager() {
  const { data, error, loading, refresh } = useResource<SeoData>("/api/admin/seo");
  const [source, setSource] = useState(""); const [target, setTarget] = useState(""); const [busy, setBusy] = useState(false); const [message, setMessage] = useState(""); const [failure, setFailure] = useState("");
  async function addRedirect() { setBusy(true); setFailure(""); try { await adminApi("/api/admin/redirects", { method: "POST", body: JSON.stringify({ source, target }) }); setSource(""); setTarget(""); setMessage("Redirect created."); await refresh(); } catch (e) { setFailure(errorMessage(e)); } finally { setBusy(false); } }
  async function remove(id: string) { if (!await confirmAction({ title: "Remove this redirect?", message: "Visitors to the old address will no longer be redirected.", confirmLabel: "Remove redirect", tone: "danger" })) return; try { await adminApi(`/api/admin/redirects/${id}`, { method: "DELETE" }); await refresh(); } catch (e) { setFailure(errorMessage(e)); } }
  return <><PageHeading title="SEO health" description="Practical content checks and useful paths for readers and search engines."><button className={s.secondary} onClick={() => void refresh()}><RefreshCw size={14} />Refresh checks</button></PageHeading><Notice message={error || failure} error /><Notice message={message} />{loading ? <Loading /> : data && <><div className={s.columns}><Card title="Content findings" action={<span className={s.badge}>{data.findings.length} findings</span>} body={false}>{data.findings.length ? data.findings.map((finding, index) => <div className={s.task} key={index}><Search size={16} /><div><div className={s.actionRow}><strong>{finding.title}</strong><Badge value={finding.severity.toUpperCase()} /></div><p className={s.muted} style={{ marginTop: 5 }}>{finding.detail}</p>{finding.href && <Link href={finding.href} className={s.tableSubtitle}>Review content ↗</Link>}</div></div>) : <Empty title="No issues found in these checks" description="Continue reviewing source accuracy, reader usefulness, and search metadata as your publication grows." />}</Card><Card title="Indexing and discovery"><p className={`${s.small} ${s.muted}`}>Production indexing must be deliberately enabled in your Cloudflare deployment. Only eligible published content is included in discovery files.</p><div className={s.actionRow}><a className={s.secondary} href="/sitemap.xml" target="_blank">Sitemap<ExternalLink size={13} /></a><a className={s.secondary} href="/robots.txt" target="_blank">Robots file<ExternalLink size={13} /></a></div><p className={`${s.small} ${s.muted}`}>These checks identify issues in your content. Search rankings and indexing depend on search engines.</p></Card></div><Card title="Redirect manager"><div className={s.fieldGrid}><Field label="Old path" hint="An internal path beginning with /."><input className={s.input} value={source} onChange={e => setSource(e.target.value)} placeholder="/old-guide" /></Field><Field label="New destination"><input className={s.input} value={target} onChange={e => setTarget(e.target.value)} placeholder="/guides/new-guide" /></Field></div><button className={s.button} disabled={busy || !source || !target} onClick={() => void addRedirect()}><Plus size={14} />{busy ? "Adding…" : "Add redirect"}</button>{data.redirects.length > 0 && <div className={s.tableWrap} style={{ marginTop: 22 }}><table className={s.table}><thead><tr><th>From</th><th>To</th><th>Action</th></tr></thead><tbody>{data.redirects.map(item => <tr key={item.id}><td>{item.source}</td><td>{item.target}</td><td><button className={s.iconButton} aria-label={`Delete redirect ${item.source}`} onClick={() => void remove(item.id)}><Trash2 size={15} /></button></td></tr>)}</tbody></table></div>}</Card></>}</>;
}

interface Contact { id: string; name: string; email: string; subject?: string; message: string; status: "NEW" | "READ" | "CLOSED"; createdAt: string }
export function Contacts() {
  const { data, error, loading, refresh } = useResource<{ items: Contact[] }>("/api/admin/contacts");
  const [selected, setSelected] = useState<Contact | null>(null); const [failure, setFailure] = useState(""); const [filter, setFilter] = useState("");
  async function update(item: Contact, status: Contact["status"]) { try { await adminApi(`/api/admin/contacts/${item.id}`, { method: "PATCH", body: JSON.stringify({ status }) }); setSelected({ ...item, status }); await refresh(); } catch (e) { setFailure(errorMessage(e)); } }
  return <><PageHeading title="Reader messages" description="Questions, corrections, and feedback submitted through your contact form."><select className={s.select} aria-label="Contact status" value={filter} onChange={e => setFilter(e.target.value)}><option value="">All messages</option><option value="NEW">New</option><option value="READ">Read</option><option value="CLOSED">Closed</option></select></PageHeading><Notice message={error || failure} error />{loading ? <Loading /> : <div className={s.columns}><Card title="Inbox" body={false}>{!data?.items.length ? <Empty title="Your inbox is clear" description="Real reader submissions will appear here. No sample messages are added." /> : data.items.filter(item => !filter || item.status === filter).map(item => <button className={s.task} key={item.id} style={{ width: "100%", textAlign: "left", background: selected?.id === item.id ? "var(--a-soft)" : "transparent", color: "inherit", borderWidth: "0 0 1px", cursor: "pointer" }} onClick={() => { setSelected(item); if (item.status === "NEW") void update(item, "READ"); }}><div style={{ flex: 1 }}><strong>{item.subject || "Reader message"}</strong><span className={s.tableSubtitle}>{item.name} · {dateLabel(item.createdAt)}</span></div><Badge value={item.status} /></button>)}</Card><Card title={selected ? selected.subject || "Message details" : "Message details"}>{selected ? <><strong>{selected.name}</strong><p className={`${s.small} ${s.muted}`}>{selected.email}</p><p style={{ whiteSpace: "pre-wrap", overflowWrap: "anywhere", fontSize: 13 }}>{selected.message}</p><div className={s.actionRow}><button className={s.secondary} onClick={() => void update(selected, selected.status === "CLOSED" ? "READ" : "CLOSED")}>{selected.status === "CLOSED" ? "Reopen message" : "Mark closed"}</button><a className={s.secondary} href={`mailto:${selected.email}`}>Open email app</a></div></> : <p className={`${s.small} ${s.muted}`}>Select a message to read it and update its status.</p>}</Card></div>}</>;
}

interface UserRecord { id: string; name: string; email: string; role: string; active: boolean; twoFactorEnabled: boolean }
export function UsersManager() {
  const { data, error, loading, refresh } = useResource<{ items: UserRecord[] }>("/api/admin/users");
  const [failure, setFailure] = useState(""); const [message, setMessage] = useState(""); const [busy, setBusy] = useState("");
  async function update(item: UserRecord, patch: { role?: string; active?: boolean }) { if (!await confirmAction({ title: `Update access for ${item.name}?`, message: "Changes take effect on their next authorized request.", confirmLabel: "Update access" })) return; setBusy(item.id); setFailure(""); try { await adminApi(`/api/admin/users/${item.id}`, { method: "PATCH", body: JSON.stringify(patch) }); setMessage("Account access updated."); await refresh(); } catch (e) { setFailure(errorMessage(e)); } finally { setBusy(""); } }
  return <><PageHeading title="Users & roles" description="Give each contributor the access they need to do their work." /><Notice message={error || failure} error /><Notice message={message} />{loading ? <Loading /> : <Card title="Workspace members" body={false}>{data?.items.length ? <div className={s.tableWrap}><table className={s.table}><thead><tr><th>Person</th><th>Role</th><th>Two-factor</th><th>Access</th><th>Actions</th></tr></thead><tbody>{data.items.map(item => <tr key={item.id}><td><strong>{item.name}</strong><span className={s.tableSubtitle}>{item.email}</span></td><td><select className={s.select} aria-label={`Role for ${item.name}`} value={item.role} disabled={busy === item.id} onChange={e => void update(item, { role: e.target.value })}>{["OWNER", "ADMIN", "EDITOR", "AUTHOR", "ANALYST"].map(role => <option value={role} key={role}>{friendly(role)}</option>)}</select></td><td><Badge value={item.twoFactorEnabled ? "ENABLED" : "NOT_ENABLED"} /></td><td><Badge value={item.active ? "ACTIVE" : "SUSPENDED"} /></td><td><button className={s.secondary} disabled={busy === item.id} onClick={() => void update(item, { active: !item.active })}>{item.active ? "Suspend" : "Restore access"}</button></td></tr>)}</tbody></table></div> : <Empty title="No members found" description="Workspace accounts will appear here after they have been created." />}</Card>}<div className={s.columns}><div><InvitationForm /><Card title="Role guide"><ul className={s.list}>{[["Owner", "Account security, configuration, and all publication operations."], ["Admin", "Publication management and ordinary account access."], ["Editor", "Research, articles, products, and publishing."], ["Author", "Their own drafts and approved reference material."], ["Analyst", "Collected traffic and affiliate click reports."]].map(([role, detail]) => <li key={role}><strong className={s.small}>{role}</strong><p className={`${s.small} ${s.muted}`} style={{ margin: "4px 0 0" }}>{detail}</p></li>)}</ul></Card></div><Card title="Secure your account"><ShieldCheck size={27} color="#578067" /><p className={`${s.small} ${s.muted}`}>Set up two-factor authentication and manage your sessions in Account security.</p><Link href="/admin/security" className={s.secondary}>Account security</Link></Card></div></>;
}

interface SystemData { jobs: { id: string; kind?: string; status: string; lastError?: string; updatedAt?: string; scheduledAt?: string }[]; audit: { id: string; action: string; actorId?: string; createdAt: string; targetId?: string }[]; integrations: Record<string, boolean | string>; environment: string | Record<string, unknown> }
export function SystemManager() {
  const { data, error, loading, refresh } = useResource<SystemData>("/api/admin/system"); const [failure, setFailure] = useState(""); const [message, setMessage] = useState("");
  async function retry(id: string) { try { await adminApi(`/api/admin/jobs/${id}`, { method: "POST", body: JSON.stringify({ action: "retry" }) }); setMessage("The job has been queued for retry."); await refresh(); } catch (e) { setFailure(errorMessage(e)); } }
  return <><PageHeading title="System & activity" description="Actual integration status, publishing jobs, and a record of important changes."><a className={s.secondary} href="/api/admin/export" download><Download size={14} />Export publication</a><button className={s.secondary} onClick={() => void refresh()}><RefreshCw size={14} />Refresh</button></PageHeading><Notice message={error || failure} error /><Notice message={message} />{loading ? <Loading /> : data && <><div className={s.grid}>{Object.entries(data.integrations).map(([key, value]) => <div className={s.stat} key={key}><div className={s.statTop}>{key === "database" ? "Cloudflare D1" : key === "storage" ? "Cloudflare R2" : friendly(key)}</div><div style={{ marginTop: 15 }}><Badge value={value === true ? "CONFIGURED" : value === false ? "NOT_CONFIGURED" : String(value).toUpperCase()} /></div></div>)}</div><Card title="Background jobs" body={false}>{data.jobs.length ? <div className={s.tableWrap}><table className={s.table}><thead><tr><th>Job</th><th>Status</th><th>Created</th><th>Action</th></tr></thead><tbody>{data.jobs.map(job => <tr key={job.id}><td>{friendly(job.kind || "Publish")}<span className={s.tableSubtitle}>{job.lastError}</span></td><td><Badge value={job.status.toUpperCase()} /></td><td>{dateLabel(job.updatedAt || job.scheduledAt)}</td><td>{job.status.toUpperCase() === "FAILED" && <button className={s.secondary} onClick={() => void retry(job.id)}>Retry job</button>}</td></tr>)}</tbody></table></div> : <Empty title="No background jobs yet" description="Scheduled publishing and other recorded jobs will appear here." />}</Card><Card title="Activity log" body={false}>{data.audit.length ? <div className={s.tableWrap}><table className={s.table}><thead><tr><th>Action</th><th>Actor</th><th>Target</th><th>Date</th></tr></thead><tbody>{data.audit.map(event => <tr key={event.id}><td>{friendly(event.action)}</td><td>{event.actorId || "System"}</td><td>{event.targetId || "—"}</td><td>{dateLabel(event.createdAt)}</td></tr>)}</tbody></table></div> : <Empty title="Your activity log is ready" description="Publishing, account changes, and configuration updates will be recorded here." />}</Card></>}</>;
}

export function Help() {
  const guides = [{ icon: FileCheck2, title: "Publish your first useful guide", steps: ["Create a real author profile with relevant experience.", "Add sources and reviewed product records to your research.", "Create an article, choose its category, and write your draft.", "Review the desktop and mobile preview. Check links and image descriptions.", "Submit for review, approve, and publish when the checks pass."], href: "/admin/articles/new", action: "Start a new article" }, { icon: BookOpen, title: "Prepare your publication for launch", steps: ["Review your About, Contact, privacy, and affiliate disclosure pages.", "Add your approved Amazon Associates tracking tag.", "Configure your header, footer, and homepage sections.", "Verify Cloudflare D1, R2, email, and the publishing scheduler.", "Enable public indexing only after reviewing the production website."], href: "/admin/settings", action: "Review website settings" }, { icon: LockKeyhole, title: "Protect your workspace", steps: ["Use a unique password and enable two-factor authentication.", "Keep recovery codes somewhere safe and separate from this account.", "Give contributors the smallest role that supports their work.", "Review active accounts and suspend access when someone leaves.", "Keep private content and original uploads in draft until reviewed."], href: "/admin/security", action: "Review account security" }, { icon: Users, title: "Maintain reader trust", steps: ["Clearly distinguish research from hands-on testing.", "Record sources and the dates you verified product claims.", "Place your affiliate disclosure before recommendations.", "Schedule regular editorial reviews and update stale claims.", "Read corrections from your contact inbox and keep meaningful revisions."], href: "/admin/contacts", action: "Open reader messages" }];
  return <><PageHeading title="A practical guide to your studio" description="Everything you need to start publishing and keep the quality high." /><div className={s.helpGrid}>{guides.map(guide => <section className={s.helpCard} key={guide.title}><guide.icon size={25} color="#588467" /><h2>{guide.title}</h2><ol>{guide.steps.map(step => <li key={step}>{step}</li>)}</ol><Link className={s.secondary} href={guide.href}>{guide.action} ↗</Link></section>)}</div></>;
}



