"use client";

import Link from "next/link";
import { ArrowRight, BarChart3, CheckCircle2, Clock3, FileText, FolderTree, Package, Plus, Sparkles } from "lucide-react";
import type { ContentRecord } from "@/lib/types";
import { dateLabel, useResource } from "./api";
import { Badge, Card, Empty, Loading, Notice, PageHeading } from "./ui";
import s from "./admin.module.css";

interface OverviewData { counts: { articles: number; products: number; categories: number; published: number; drafts: number }; recent: ContentRecord[]; tasks: string[]; events: { pageViews: number; affiliateClicks: number }; jobs: { id: string; status?: string; scheduledAt?: string; kind?: string }[] }
export function Overview() {
  const { data, error, loading, refresh } = useResource<OverviewData>("/api/admin/overview");
  if (loading && !data) return <Loading />;
  return <><PageHeading title="A clearer view of your publication." description="Keep your content useful, your research current, and your readers informed."><Link className={s.button} href="/admin/articles/new"><Plus size={16} />New article</Link></PageHeading><Notice message={error} error />{!data ? <button className={s.secondary} onClick={() => void refresh()}>Try again</button> : <>
    <div className={s.grid}>{[{ label: "Total articles", value: data.counts.articles, detail: `${data.counts.drafts} drafts in progress`, icon: FileText }, { label: "Published content", value: data.counts.published, detail: "Available to your readers", icon: CheckCircle2 }, { label: "Product library", value: data.counts.products, detail: "Editorial product records", icon: Package }, { label: "Categories", value: data.counts.categories, detail: "Organize your expertise", icon: FolderTree }].map(stat => <div className={s.stat} key={stat.label}><div className={s.statTop}>{stat.label}<span className={s.statIcon}><stat.icon size={17} strokeWidth={1.7} /></span></div><strong>{stat.value.toLocaleString()}</strong><small>{stat.detail}</small></div>)}</div>
    {data.counts.published === 0 && <div className={s.welcome}><div><span className={s.welcomeEyebrow}><Sparkles size={12} />A thoughtful start</span><h2>Your next useful guide starts here.</h2><p>Set up your author profile, add verified product research, and publish when your first article is ready. Drafts stay private while you work.</p><ol className={s.welcomeSteps}>{["Author profile", "Product research", "Publish"].map((step, i) => <li key={step}><span>{i + 1}</span>{step}</li>)}</ol></div><Link className={s.button} href="/admin/help">Your launch checklist<ArrowRight size={15} /></Link></div>}
    <div className={s.columns}><div><Card title="Recently updated" action={<Link className={s.small} href="/admin/articles">All articles <span aria-hidden="true">↗</span></Link>} body={false}>{data.recent.length ? <div className={s.tableWrap}><table className={s.table}><thead><tr><th>Content</th><th>Status</th><th>Updated</th></tr></thead><tbody>{data.recent.map(record => <tr key={record.id}><td><Link className={s.tableTitle} href={`/admin/${record.kind === "article" ? "articles" : record.kind === "product" ? "products" : "pages"}/${record.id}`}>{record.data.title || "Untitled draft"}</Link><span className={s.tableSubtitle}>{record.kind === "article" ? record.data.articleType.toLowerCase().replaceAll("_", " ") : record.kind}</span></td><td><Badge value={record.workflow} /></td><td className={s.muted}>{dateLabel(record.updatedAt)}</td></tr>)}</tbody></table></div> : <Empty title="A blank page, full of possibility" description="Your articles, product records, and pages will appear here as you create them."><Link href="/admin/articles/new" className={s.secondary}>Create your first article</Link></Empty>}</Card>
    <Card title="Reader activity" action={<Link className={s.small} href="/admin/analytics">View analytics ↗</Link>}>{data.events.pageViews || data.events.affiliateClicks ? <div className={s.fieldGrid}><div><span className={s.muted}>Collected page views</span><h2>{data.events.pageViews.toLocaleString()}</h2></div><div><span className={s.muted}>Affiliate clicks</span><h2>{data.events.affiliateClicks.toLocaleString()}</h2></div></div> : <Empty title="Your audience story is still ahead" description="Collected page views and affiliate clicks will appear after your website starts receiving readers. Analytics can be enabled in Settings." />}</Card></div>
    <div><Card title="Needs your attention" action={<span className={s.badge}>{data.tasks.length} tasks</span>} body={false}>{data.tasks.length ? data.tasks.map((task, index) => <div className={s.task} key={index}><Clock3 size={16} /><p>{task}</p></div>) : <div className={s.task}><CheckCircle2 size={17} /><p>No outstanding editorial tasks. Keep reviewing your published research regularly.</p></div>}</Card><Card title="Publishing queue" body={false}>{data.jobs.length ? data.jobs.slice(0, 5).map(job => <div className={s.task} key={job.id}><Clock3 size={16} /><div>{job.kind || "Scheduled publication"}<div className={s.tableSubtitle}>{dateLabel(job.scheduledAt)} · {job.status || "Pending"}</div></div></div>) : <Empty title="Nothing scheduled" description="Schedule a reviewed draft from its editor when you are ready to choose a publishing time." />}</Card><Card title="Built around reader trust"><div className={s.actionRow}><BarChart3 size={24} color="#558061" /><p className={`${s.small} ${s.muted}`} style={{ margin: 0 }}>Clicks show reader interest. Amazon earnings and purchases are available through your Associates account.</p></div></Card></div></div>
  </>}</>;
}

