"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { ArrowDown, ArrowUp, Plus, Save, Trash2 } from "lucide-react";
import type { SiteSettings } from "@/lib/types";
import { adminApi, errorMessage, useResource } from "./api";
import { Card, Field, Loading, Notice, PageHeading } from "./ui";
import s from "./admin.module.css";

export function SettingsManager({ section }: { section: "settings" | "navigation" | "homepage" | "affiliate" }) {
  const { data, error, loading } = useResource<{ settings: SiteSettings }>("/api/admin/settings");
  const [editedSettings, setSettings] = useState<SiteSettings | null>(null);
  const settings = editedSettings || data?.settings || null;
  const [message, setMessage] = useState("");
  const [failure, setFailure] = useState("");
  const [busy, setBusy] = useState(false);
  const [dirty, setDirty] = useState(false);
  useEffect(() => { const handler = (event: BeforeUnloadEvent) => { if (dirty) event.preventDefault(); }; window.addEventListener("beforeunload", handler); return () => window.removeEventListener("beforeunload", handler); }, [dirty]);
  function update<K extends keyof SiteSettings>(key: K, value: SiteSettings[K]) { if (settings) setSettings({ ...settings, [key]: value }); setDirty(true); setMessage(""); }
  async function save() { if (!settings) return; setBusy(true); setFailure(""); try { const result = await adminApi<{ settings: SiteSettings }>("/api/admin/settings", { method: "PUT", body: JSON.stringify(settings) }); setSettings(result.settings); setDirty(false); setMessage("Your changes have been saved."); } catch (e) { setFailure(errorMessage(e)); } finally { setBusy(false); } }
  const titles = { settings: "Website settings", navigation: "Navigation", homepage: "Home page", affiliate: "Affiliate links" };
  const descriptions = { settings: "Make this publication your own. Manage its identity and reader preferences.", navigation: "Help readers find the right guide with simple, useful menus.", homepage: "Choose which editorial sections readers see and the order they appear.", affiliate: "Manage your Amazon Associates tag and review your affiliate setup." };
  if (loading) return <Loading />;
  return <><PageHeading title={titles[section]} description={descriptions[section]}><span className={s.saveState}>{dirty ? "Unsaved changes" : "All changes saved"}</span><button className={s.button} disabled={busy || !settings || !dirty} onClick={() => void save()}><Save size={15} />{busy ? "Saving…" : "Save changes"}</button></PageHeading><Notice message={error || failure} error /><Notice message={message} />{settings && <>
    {section === "settings" && <div className={s.columns}><div><Card title="Publication identity"><Field label="Publication name"><input className={s.input} value={settings.brandName} onChange={e => update("brandName", e.target.value)} /></Field><Field label="Tagline"><input className={s.input} value={settings.tagline} onChange={e => update("tagline", e.target.value)} /></Field><Field label="Site description" hint="A clear description of who your publication helps and what it covers."><textarea className={s.textarea} value={settings.siteDescription} onChange={e => update("siteDescription", e.target.value)} /></Field><Field label="Public contact email"><input type="email" className={s.input} value={settings.contactEmail} onChange={e => update("contactEmail", e.target.value)} /></Field><Field label="Editorial timezone" hint="Use an IANA timezone, such as Asia/Karachi or America/New_York."><input className={s.input} value={settings.timezone} onChange={e => update("timezone", e.target.value)} /></Field></Card><Card title="Privacy and optional features"><label className={s.check}><input type="checkbox" checked={settings.analyticsEnabled} onChange={e => update("analyticsEnabled", e.target.checked)} />Collect anonymous page views and affiliate clicks</label><label className={s.check}><input type="checkbox" checked={settings.privacyReviewed} onChange={e => update("privacyReviewed", e.target.checked)} />The owner has reviewed the publication’s privacy information</label><label className={s.check}><input type="checkbox" checked={settings.newsletterEnabled} onChange={e => update("newsletterEnabled", e.target.checked)} />Enable newsletter signup</label><p className={`${s.small} ${s.muted}`}>Newsletter signup requires configured delivery and a reviewed consent workflow. The server checks integration readiness when saving.</p></Card></div><div><Card title="Connected services"><p className={`${s.small} ${s.muted}`}>Cloudflare D1 stores your content. Media lives in Cloudflare R2. Integration credentials are managed in Cloudflare.</p><Link className={s.secondary} href="/admin/system">View configuration status</Link></Card><Card title="More ways to customize"><div className={s.list}>{[{ label: "Header and footer menus", href: "navigation" }, { label: "Homepage sections", href: "homepage" }, { label: "Amazon affiliate tag", href: "affiliate" }].map(item => <div className={s.splitLine} key={item.href}><Link href={`/admin/${item.href}`}>{item.label} ↗</Link></div>)}</div></Card></div></div>}
    {section === "affiliate" && <div className={s.columns}><div><Card title="Amazon Associates"><Field label="Amazon.com tracking tag" hint="Find this in your Amazon Associates account. Example format: yourtag-20."><input className={s.input} value={settings.affiliateTag} onChange={e => update("affiliateTag", e.target.value)} placeholder="yourtag-20" /></Field><Notice message={settings.affiliateTag ? "Product links use your saved tracking tag. Verify your Associates account and approved website independently before publishing." : "Add your approved tracking tag before publishing affiliate product links."} /><p className={`${s.small} ${s.muted}`}>The publication does not display live prices or availability until compliant catalog access is configured.</p></Card><Card title="Link checks and activity"><p className={`${s.small} ${s.muted}`}>Review product destinations in your library and collected clicks in Analytics. A recorded click does not indicate a purchase.</p><div className={s.actionRow}><Link className={s.secondary} href="/admin/products">Review products</Link><Link className={s.secondary} href="/admin/seo">Check content issues</Link><Link className={s.secondary} href="/admin/analytics">View collected clicks</Link></div></Card></div><Card title="Reader disclosure"><p className={s.small}>As an Amazon Associate, we earn from qualifying purchases.</p><p className={`${s.small} ${s.muted}`}>Place the disclosure where readers can see it before affiliate recommendations. Use the disclosure block in your article editor.</p></Card></div>}
    {section === "navigation" && <Card title="Header and footer links" action={<button className={s.secondary} onClick={() => update("navigation", [...settings.navigation, { label: "", href: "", location: "header" }])}><Plus size={14} />Add link</button>}>{settings.navigation.map((item, index) => <div className={s.repeatedRow} key={index}><div className={s.fieldGrid}><Field label="Link label"><input className={s.input} value={item.label} onChange={e => update("navigation", settings.navigation.map((link, i) => i === index ? { ...link, label: e.target.value } : link))} /></Field><Field label="Destination" hint="A published path like /guides or a permitted https:// URL."><input className={s.input} value={item.href} onChange={e => update("navigation", settings.navigation.map((link, i) => i === index ? { ...link, href: e.target.value } : link))} /></Field></div><div className={s.actionRow}><select className={s.select} aria-label="Menu location" value={item.location} onChange={e => update("navigation", settings.navigation.map((link, i) => i === index ? { ...link, location: e.target.value as "header" | "footer" } : link))}><option value="header">Header menu</option><option value="footer">Footer menu</option></select><button className={s.secondary} disabled={index === 0} onClick={() => { const items = [...settings.navigation]; [items[index - 1], items[index]] = [items[index], items[index - 1]]; update("navigation", items); }} aria-label="Move link up"><ArrowUp size={14} /></button><button className={s.secondary} disabled={index === settings.navigation.length - 1} onClick={() => { const items = [...settings.navigation]; [items[index + 1], items[index]] = [items[index], items[index + 1]]; update("navigation", items); }} aria-label="Move link down"><ArrowDown size={14} /></button><button className={s.secondary} onClick={() => update("navigation", settings.navigation.filter((_, i) => i !== index))}><Trash2 size={14} />Remove</button></div></div>)}{!settings.navigation.length && <p className={s.muted}>Add a link to start building your navigation.</p>}</Card>}
    {section === "homepage" && <div className={s.columns}><Card title="Homepage sections">{settings.homeSections.map((sectionItem, index) => <div className={s.sortRow} key={sectionItem.id}><label className={s.check} title="Show section"><input aria-label={`Show ${sectionItem.title}`} type="checkbox" checked={sectionItem.visible} onChange={e => update("homeSections", settings.homeSections.map((item, i) => i === index ? { ...item, visible: e.target.checked } : item))} /></label><input className={s.input} aria-label="Section heading" value={sectionItem.title} onChange={e => update("homeSections", settings.homeSections.map((item, i) => i === index ? { ...item, title: e.target.value } : item))} /><button className={s.iconButton} disabled={index === 0} onClick={() => { const items = [...settings.homeSections]; [items[index - 1], items[index]] = [items[index], items[index - 1]]; update("homeSections", items); }} aria-label="Move section up"><ArrowUp size={16} /></button><button className={s.iconButton} disabled={index === settings.homeSections.length - 1} onClick={() => { const items = [...settings.homeSections]; [items[index + 1], items[index]] = [items[index], items[index + 1]]; update("homeSections", items); }} aria-label="Move section down"><ArrowDown size={16} /></button></div>)}</Card><Card title="Curate your homepage"><p className={`${s.small} ${s.muted}`}>Mark a reviewed article as “Featured” in its editor to include it in featured selections. Only published content appears to readers.</p><div className={s.actionRow}><Link className={s.secondary} href="/admin/articles">Choose articles</Link><Link className={s.secondary} target="_blank" href="/">View homepage ↗</Link></div></Card></div>}
  </>}</>;
}
