import "server-only";
import { getDB,getEnv } from "./db";
import { audit, AppError, now } from "./editorial";
import { getSettings,listAdminContent,listPublicContent,listCategories,listAuthors } from "./content";
import { categorySchema, authorSchema, tagSchema, settingsSchema } from "@/lib/validation";
import { requireRole, type User } from "./auth";
import { ADMIN_ROLES, EDITOR_ROLES } from "./permissions";
import type { MediaAsset } from "@/lib/types";
type Row=Record<string,unknown>;
export async function overview(user:User){const db=await getDB();if(user.role==="ANALYST"){const [articles,products,categories,events]=await Promise.all([listPublicContent({kind:"article",pageSize:1}),listPublicContent({kind:"product",pageSize:1}),listCategories(),analytics(user)]);return {counts:{articles:articles.total,products:products.total,published:articles.total,drafts:0,categories:categories.length},recent:[],tasks:[],events:{pageViews:events.pageViews,affiliateClicks:events.affiliateClicks},jobs:[]};}const own=user.role==="AUTHOR"?" AND c.created_by=?":"";const args=own?[user.id]:[];const count=async(kind:string,extra="")=>(await db.prepare(`SELECT count(*) n FROM content_records c WHERE c.kind=? AND c.state<>'TRASHED'${extra}${own}`).bind(kind,...args).first<{n:number}>())?.n??0;const settings=await getSettings();const [articles,products,published,drafts,categories,recent,events,jobs]=await Promise.all([count("article"),count("product"),count("article"," AND c.state='PUBLISHED'"),count("article"," AND c.draft_revision_id IS NOT NULL"),listCategories(true),listAdminContent({kind:"article",createdBy:own?user.id:undefined}),analytics(user),db.prepare("SELECT id,kind,status,scheduled_at as scheduledAt,last_error as lastError FROM jobs WHERE status IN('PENDING','FAILED') ORDER BY scheduled_at LIMIT 10").all<Row>()]);const tasks:string[]=[];if(!settings.affiliateTag)tasks.push("Configure your Amazon Associates tracking tag.");if(!(await listAuthors()).some(a=>a.biography))tasks.push("Add your public author biography.");if(!settings.contactEmail)tasks.push("Set the contact destination.");if(!settings.privacyReviewed)tasks.push("Review privacy and trust pages before launch.");if(!user.twoFactorEnabled&&["OWNER","ADMIN"].includes(user.role))tasks.unshift("Set up two-factor authentication in Account security.");if(!published)tasks.push("Write, review, and publish your first article.");return {counts:{articles,products,published,drafts,categories:categories.length},recent:recent.items.slice(0,6),tasks,events:{pageViews:events.pageViews,affiliateClicks:events.affiliateClicks},jobs:jobs.results};}
export async function analytics(user:User,days=30){const db=await getDB();const start=new Date(Date.now()-Math.min(365,Math.max(1,days))*86400000).toISOString();const own=user.role==="AUTHOR"?" AND article_id IN(SELECT id FROM content_records WHERE created_by=?)":"";const args=own?[start,user.id]:[start];const totals=await db.prepare(`SELECT coalesce(sum(event_type='page_view'),0) pageViews,coalesce(sum(event_type='affiliate_click'),0) affiliateClicks FROM analytics_events WHERE created_at>=?${own}`).bind(...args).first<{pageViews:number;affiliateClicks:number}>();const daily=await db.prepare(`SELECT substr(created_at,1,10) date,sum(event_type='page_view') pageViews,sum(event_type='affiliate_click') affiliateClicks FROM analytics_events WHERE created_at>=?${own} GROUP BY date ORDER BY date`).bind(...args).all();const topPages=await db.prepare(`SELECT path,sum(event_type='page_view') views,sum(event_type='affiliate_click') clicks FROM analytics_events WHERE created_at>=?${own} GROUP BY path ORDER BY views DESC LIMIT 20`).bind(...args).all();return {...totals,pageViews:totals?.pageViews??0,affiliateClicks:totals?.affiliateClicks??0,daily:daily.results,topPages:topPages.results};}
export async function listTaxonomy(resource:string,user:User){requireRole(user,[...EDITOR_ROLES,"AUTHOR"]);const db=await getDB();if(resource==="categories")return listCategories(true);if(resource==="authors")return listAuthors();if(resource==="tags"){const {results}=await db.prepare("SELECT * FROM tags ORDER BY name LIMIT 1000").all<Row>();return results.map(r=>({...r,indexable:!!r.indexable}));}throw new AppError("Unknown collection.",404);}
export async function saveTaxonomy(resource:string,id:string|undefined,value:unknown,user:User){requireRole(user,EDITOR_ROLES);const db=await getDB(),key=id??crypto.randomUUID();if(id&&!await db.prepare(`SELECT id FROM ${resource==="categories"?"categories":resource==="authors"?"authors":"tags"} WHERE id=?`).bind(id).first())throw new AppError("Record not found.",404);
 if(resource==="categories"){const c=categorySchema.parse(value);if(c.parentId){let parent:string|null=c.parentId;const seen=new Set([key]);while(parent){if(seen.has(parent))throw new AppError("Categories cannot form a parent cycle.");seen.add(parent);const row: {parent_id:string|null}|null=await db.prepare("SELECT parent_id FROM categories WHERE id=?").bind(parent).first();if(!row)throw new AppError("Parent category does not exist.");parent=row.parent_id;}}await db.prepare("INSERT INTO categories(id,name,slug,description,parent_id,icon,sort_order,visible,seo_title,seo_description,attributes) VALUES(?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET name=excluded.name,slug=excluded.slug,description=excluded.description,parent_id=excluded.parent_id,icon=excluded.icon,sort_order=excluded.sort_order,visible=excluded.visible,seo_title=excluded.seo_title,seo_description=excluded.seo_description,attributes=excluded.attributes").bind(key,c.name,c.slug,c.description,c.parentId||null,c.icon,c.sortOrder,+c.visible,c.seoTitle,c.seoDescription,JSON.stringify(c.attributes)).run();}
 else if(resource==="authors"){const a=authorSchema.parse(value);await db.prepare("INSERT INTO authors(id,name,slug,biography,image,links,user_id) VALUES(?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET name=excluded.name,slug=excluded.slug,biography=excluded.biography,image=excluded.image,links=excluded.links,user_id=excluded.user_id").bind(key,a.name,a.slug,a.biography,a.image,JSON.stringify(a.links),a.userId).run();}
 else if(resource==="tags"){const t=tagSchema.parse(value);await db.prepare("INSERT INTO tags(id,name,slug,description,indexable) VALUES(?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET name=excluded.name,slug=excluded.slug,description=excluded.description,indexable=excluded.indexable").bind(key,t.name,t.slug,t.description,+t.indexable).run();}else throw new AppError("Unknown collection.",404);
 await audit(user.id,`${resource}.save`,key);return (await listTaxonomy(resource,user)).find(item=>"id" in item&&item.id===key);
}
export async function deleteTaxonomy(resource:string,id:string,user:User){requireRole(user,EDITOR_ROLES);if(!["categories","authors","tags"].includes(resource))throw new AppError("Unknown collection.",404);const db=await getDB();const usage=await db.prepare("SELECT r.id FROM revisions r,json_tree(r.data) t WHERE t.type='text' AND t.value=? LIMIT 1").bind(id).first();if(usage)throw new AppError("This record is referenced by content or revision history. Reassign or retain it to protect those references.",409);await db.prepare(`DELETE FROM ${resource} WHERE id=?`).bind(id).run();await audit(user.id,`${resource}.delete`,id);}
export async function saveSettings(value:unknown,user:User){requireRole(user,ADMIN_ROLES);const settings=settingsSchema.parse(value);const current=await getSettings();if(user.role!=="OWNER"&&(settings.affiliateTag!==current.affiliateTag||settings.analyticsEnabled!==current.analyticsEnabled||settings.newsletterEnabled!==current.newsletterEnabled||settings.contactEmail!==current.contactEmail))throw new AppError("Only the owner may change integration settings.",403);if(settings.newsletterEnabled)throw new AppError("Newsletter delivery is not configured. Keep this feature disabled until delivery is verified.");const db=await getDB();await db.prepare("UPDATE settings SET data=?,updated_at=? WHERE id='site'").bind(JSON.stringify(settings),now()).run();await audit(user.id,"settings.save","site");return settings;}
export function mapMedia(r:Row):MediaAsset{return {id:String(r.id),key:String(r.key),filename:String(r.filename),contentType:String(r.content_type),size:Number(r.size),alt:String(r.alt),credit:String(r.credit),license:String(r.license),visibility:r.visibility as MediaAsset["visibility"],createdBy:String(r.created_by),createdAt:String(r.created_at)};}
export async function listMedia(user:User){requireRole(user,[...EDITOR_ROLES,"AUTHOR"]);const db=await getDB();const own=user.role==="AUTHOR"?" WHERE created_by=? OR visibility='PUBLIC'":"";return (await db.prepare(`SELECT * FROM media_assets${own} ORDER BY created_at DESC LIMIT 200`).bind(...(own?[user.id]:[])).all<Row>()).results.map(mapMedia);}
export async function systemStatus(user:User){requireRole(user,ADMIN_ROLES);const [db,env]=await Promise.all([getDB(),getEnv()]);const [jobs,audit]=await Promise.all([db.prepare("SELECT id,kind,status,attempts,scheduled_at as scheduledAt,last_error as lastError,updated_at as updatedAt FROM jobs ORDER BY updated_at DESC LIMIT 100").all(),db.prepare("SELECT id,actor_id as actorId,action,target_id as targetId,created_at as createdAt FROM audit_log ORDER BY created_at DESC LIMIT 100").all()]);return {jobs:jobs.results,audit:audit.results,integrations:{database:"Cloudflare D1 connected",storage:env.MEDIA?"Cloudflare R2 bound":"Not configured",email:env.RESEND_API_KEY&&env.EMAIL_FROM?"Configured; delivery requires verification":"Not configured",amazon:"Manual links; catalog API disabled"},environment:env.APP_ENV};}
export async function seoReport(user:User){requireRole(user,EDITOR_ROLES);const db=await getDB();const {results}=await db.prepare("SELECT c.id,c.kind,c.state,c.public_path,r.data FROM content_records c JOIN revisions r ON r.id=coalesce(c.draft_revision_id,c.live_revision_id) WHERE c.state<>'TRASHED' LIMIT 1000").all<Row>();const findings:{severity:string;title:string;detail:string;href:string}[]=[];const titles=new Set<string>();for(const r of results){const d=JSON.parse(String(r.data));const href=`/admin/${r.kind==='article'?'articles':r.kind==='product'?'products':'pages'}/${r.id}`;const add=(title:string,detail:string,severity="warning")=>findings.push({title,detail,severity,href});if(!d.seoDescription)add("Missing search description",String(d.title||"Untitled"));if(titles.has(d.title))add("Duplicate title",d.title);titles.add(d.title);if(d.image&&!d.imageAlt)add("Missing image alt text",d.title,"error");if(d.reviewDueAt&&new Date(d.reviewDueAt).valueOf()<Date.now())add("Editorial review is due",d.title);if(r.state==='PUBLISHED'&&d.noindex)add("Published content is noindex",d.title,"info");}const redirects=await db.prepare("SELECT id,source,target FROM redirects ORDER BY created_at DESC LIMIT 500").all();return {findings,redirects:redirects.results};}
export async function saveRedirect(value:Record<string,unknown>,user:User){requireRole(user,EDITOR_ROLES);const {source,target}=value;if(typeof source!=="string"||typeof target!=="string"||![source,target].every(p=>/^\/[a-z0-9][a-z0-9/-]*$/.test(p))||source===target||[source,target].some(p=>/^\/(admin|api|preview)(\/|$)/.test(p)))throw new AppError("Use different, valid public paths.");const db=await getDB();if(await db.prepare("SELECT id FROM content_records WHERE public_path=? AND state='PUBLISHED' UNION SELECT id FROM redirects WHERE source=? LIMIT 1").bind(source,source).first())throw new AppError("The source path is already in use.");if(await db.prepare("SELECT id FROM redirects WHERE source=?").bind(target).first())throw new AppError("Choose a final destination, not another redirect.");if(!await db.prepare("SELECT id FROM content_records WHERE public_path=? AND state='PUBLISHED'").bind(target).first())throw new AppError("The destination must be a published content path.");const id=crypto.randomUUID();await db.prepare("INSERT INTO redirects(id,source,target,created_at) VALUES(?,?,?,?)").bind(id,source,target,now()).run();await audit(user.id,"redirect.create",id);return {id,source,target};}
