import "server-only";
import { getDB } from "./db";
import { defaultContent, type Author, type Category, type ContentRecord, type ListResult, type SiteSettings } from "@/lib/types";
type Row=Record<string,unknown>;
export function mapContent(r:Row):ContentRecord {return {id:String(r.id),kind:r.kind as ContentRecord["kind"],state:r.state as ContentRecord["state"],createdBy:String(r.created_by),version:Number(r.version),isDemo:!!r.is_demo,createdAt:String(r.created_at),updatedAt:String(r.updated_at),publishedAt:r.published_at as string|null,liveRevisionId:r.live_revision_id as string|null,draftRevisionId:r.draft_revision_id as string|null,data:{...defaultContent,...JSON.parse(String(r.data))},revisionId:String(r.revision_id),workflow:r.workflow as ContentRecord["workflow"]};}
export const recordSelect="SELECT c.*, r.id as revision_id, r.data, r.workflow FROM content_records c JOIN revisions r ON r.id = ";
export async function getSettings():Promise<SiteSettings>{const db=await getDB();const row=await db.prepare("SELECT data FROM settings WHERE id='site'").first<{data:string}>();if(!row)throw new Error("Database needs seed data. Run npm run db:seed.");return JSON.parse(row.data);}
export async function listCategories(includeHidden=false):Promise<Category[]>{const db=await getDB();const {results}=await db.prepare(`SELECT * FROM categories ${includeHidden?"":"WHERE visible=1"} ORDER BY sort_order,name`).all<Row>();return results.map(r=>({id:String(r.id),name:String(r.name),slug:String(r.slug),description:String(r.description),parentId:r.parent_id as string|null,icon:String(r.icon),sortOrder:Number(r.sort_order),visible:!!r.visible,seoTitle:String(r.seo_title),seoDescription:String(r.seo_description),attributes:JSON.parse(String(r.attributes))}));}
export async function getCategory(slug:string){return (await listCategories()).find(c=>c.slug===slug)??null;}
export async function listAuthors():Promise<Author[]>{const db=await getDB();const {results}=await db.prepare("SELECT id,name,slug,biography,image,links FROM authors ORDER BY name LIMIT 500").all<Row>();return results.map(r=>({id:String(r.id),name:String(r.name),slug:String(r.slug),biography:String(r.biography),image:String(r.image),links:JSON.parse(String(r.links)),userId:null}));}
export async function getAuthor(slug:string){return (await listAuthors()).find(a=>a.slug===slug)??null;}
export async function getTag(slug:string){const db=await getDB();const row=await db.prepare("SELECT id,name,slug,description,indexable FROM tags WHERE slug=?").bind(slug).first<{id:string;name:string;slug:string;description:string;indexable:number}>();return row?{...row,indexable:!!row.indexable}:null;}
export interface PublicQuery {kind?:string;type?:string;category?:string;tag?:string;author?:string;q?:string;page?:number;pageSize?:number;featured?:boolean}
export async function listPublicContent(query:PublicQuery={}):Promise<ListResult<ContentRecord>>{
 const db=await getDB();const page=Math.max(1,Math.trunc(query.page??1));const pageSize=Math.min(50,Math.max(1,Math.trunc(query.pageSize??12)));
 const where=["c.state='PUBLISHED'","c.is_demo=0","c.kind=?"];const args:(string|number)[]=[query.kind??"article"];
 if(query.type){where.push("json_extract(r.data,'$.articleType')=?");args.push(query.type);}
 for(const [key,field] of [["category","categoryIds"],["tag","tagIds"]] as const){if(query[key]){where.push(`EXISTS (SELECT 1 FROM json_each(r.data,'$.${field}') WHERE value=?)`);args.push(query[key]!);}}
 if(query.author){where.push("json_extract(r.data,'$.authorId')=?");args.push(query.author);}
 if(query.featured){where.push("json_extract(r.data,'$.featured')=1");}
 if(query.q){const words=query.q.slice(0,200).match(/[\p{L}\p{N}]+/gu)?.slice(0,12)??[];if(words.length){where.push("c.id IN (SELECT content_id FROM public_search WHERE public_search MATCH ?)");args.push(words.map(w=>`"${w}"*`).join(" AND "));}else{where.push("0=1");}}
 const from=`FROM content_records c JOIN revisions r ON r.id=c.live_revision_id WHERE ${where.join(" AND ")}`;
 const [count,rows]=await Promise.all([db.prepare(`SELECT count(*) as n ${from}`).bind(...args).first<{n:number}>(),db.prepare(`SELECT c.*,coalesce(c.live_updated_at,c.published_at) as updated_at,r.id as revision_id,r.data,r.workflow ${from} ORDER BY c.published_at DESC,c.id LIMIT ? OFFSET ?`).bind(...args,pageSize,(page-1)*pageSize).all<Row>()]);
 const total=count?.n??0;return {items:rows.results.map(mapContent),total,page,pageSize,pages:Math.max(1,Math.ceil(total/pageSize))};
}
export async function getPublicContentByPath(path:string){const db=await getDB();const row=await db.prepare(`${recordSelect}c.live_revision_id WHERE c.public_path=? AND c.state='PUBLISHED' AND c.is_demo=0 AND c.kind<>'product'`).bind(path).first<Row>();return row?{...mapContent(row),updatedAt:String(row.live_updated_at??row.published_at)}:null;}
export async function getPublicProduct(id:string){const db=await getDB();const row=await db.prepare(`${recordSelect}c.live_revision_id WHERE c.id=? AND c.state='PUBLISHED' AND c.is_demo=0 AND c.kind='product'`).bind(id).first<Row>();return row?{...mapContent(row),updatedAt:String(row.live_updated_at??row.published_at)}:null;}
export async function getPublicContentById(id:string){const db=await getDB();const row=await db.prepare(`${recordSelect}c.live_revision_id WHERE c.id=? AND c.state='PUBLISHED' AND c.is_demo=0`).bind(id).first<Row>();return row?{...mapContent(row),updatedAt:String(row.live_updated_at??row.published_at)}:null;}
export async function getRedirect(path:string):Promise<string|null>{const db=await getDB();return (await db.prepare("SELECT target FROM redirects WHERE source=?").bind(path).first<{target:string}>())?.target??null;}
export async function getRecord(id:string){const db=await getDB();const row=await db.prepare(`${recordSelect}coalesce(c.draft_revision_id,c.live_revision_id) WHERE c.id=?`).bind(id).first<Row>();return row?mapContent(row):null;}
export async function listAdminContent(query:{kind?:string;q?:string;state?:string;type?:string;page?:number;createdBy?:string}):Promise<ListResult<ContentRecord>>{
 const db=await getDB();const clauses=["c.kind=?"];const args:(string|number)[]=[query.kind??"article"];if(query.q){clauses.push("instr(lower(json_extract(r.data,'$.title')),lower(?))>0");args.push(query.q.slice(0,200));}if(query.state){clauses.push("(c.state=? OR r.workflow=?)");args.push(query.state,query.state);}else clauses.push("c.state<>'TRASHED'");if(query.createdBy){clauses.push("c.created_by=?");args.push(query.createdBy);}if(query.type){clauses.push("json_extract(r.data,'$.articleType')=?");args.push(query.type);}
 const from=`FROM content_records c JOIN revisions r ON r.id=coalesce(c.draft_revision_id,c.live_revision_id) WHERE ${clauses.join(" AND ")}`;const page=Math.max(1,query.page??1),pageSize=20;
 const [count,rows]=await Promise.all([db.prepare(`SELECT count(*) n ${from}`).bind(...args).first<{n:number}>(),db.prepare(`SELECT c.*,r.id as revision_id,r.data,r.workflow ${from} ORDER BY c.updated_at DESC LIMIT ? OFFSET ?`).bind(...args,pageSize,(page-1)*pageSize).all<Row>()]);const total=count?.n??0;return {items:rows.results.map(mapContent),total,page,pageSize,pages:Math.max(1,Math.ceil(total/pageSize))};
}
