import "server-only";
import { ZodError } from "zod";
import { AppError } from "./editorial";
import { AuthorizationError } from "./auth";
import { getDB, getEnv } from "./db";
export function json(value:unknown,status=200){return Response.json(value,{status,headers:{"Cache-Control":"private, no-store","X-Robots-Tag":"noindex"}});}
export function apiError(error:unknown){if(error instanceof ZodError)return json({error:error.issues.map(i=>`${i.path.join(".")}: ${i.message}`).join(" ")},400);if(error instanceof AppError||error instanceof AuthorizationError)return json({error:error.message},error.status);if(error instanceof Error&&/UNIQUE constraint failed/.test(error.message))return json({error:"This name, slug, or path is already in use."},409);console.error("Request failed",error instanceof Error?error.name:"UnknownError");return json({error:"The request could not be completed. Try again or check the system status."},500);}
export async function body(request:Request,maxBytes=350000):Promise<Record<string,unknown>>{if(Number(request.headers.get("content-length")??0)>maxBytes)throw new AppError("Request is too large.",413);const text=await request.text();if(text.length>maxBytes)throw new AppError("Request is too large.",413);try{const data=JSON.parse(text);if(!data||typeof data!=="object"||Array.isArray(data))throw new Error();return data;}catch{throw new AppError("Send a valid JSON object.");}}
export async function rateLimit(request:Request,scope:string,max:number,seconds:number){const [db,env]=await Promise.all([getDB(),getEnv()]);const ip=request.headers.get("cf-connecting-ip")??"local";const hashed=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(`${env.BETTER_AUTH_SECRET}:${scope}:${ip}`));const key=scope+":"+Array.from(new Uint8Array(hashed)).map(v=>v.toString(16).padStart(2,"0")).join("");const now=Math.floor(Date.now()/1000);const row=await db.prepare("INSERT INTO rate_limits(key,count,reset_at) VALUES(?,1,?) ON CONFLICT(key) DO UPDATE SET count=CASE WHEN reset_at<=? THEN 1 ELSE count+1 END,reset_at=CASE WHEN reset_at<=? THEN ? ELSE reset_at END RETURNING count").bind(key,now+seconds,now,now,now+seconds).first<{count:number}>();if((row?.count??0)>max)throw new AppError("Too many requests. Please try again shortly.",429);}
