import "server-only";
import {z} from "zod";
import {getDB,getEnv} from "./db";
import {requireRole,type User} from "./auth";
import {EDITOR_ROLES,WRITER_ROLES} from "./permissions";
import {audit,AppError,now} from "./editorial";
import {mapMedia} from "./admin";
export async function uploadMedia(request:Request,user:User){
 requireRole(user,WRITER_ROLES);if(Number(request.headers.get("content-length")??0)>9*1024*1024)throw new AppError("Images must be smaller than 8 MB.",413);
 const form=await request.formData(),file=form.get("file");if(!(file instanceof File)||file.size>8*1024*1024||file.size<12)throw new AppError("Choose a PNG, JPEG, or WebP image under 8 MB.");
 const alt=z.string().trim().min(1).max(500).parse(form.get("alt")),credit=z.string().max(500).parse(form.get("credit")??""),license=z.string().trim().min(1).max(500).parse(form.get("license"));
 const bytes=new Uint8Array(await file.arrayBuffer());let type="",ext="";if([137,80,78,71,13,10,26,10].every((v,i)=>bytes[i]===v)){type="image/png";ext="png";}else if(bytes[0]===255&&bytes[1]===216&&bytes[2]===255){type="image/jpeg";ext="jpg";}else if(new TextDecoder().decode(bytes.slice(0,4))==="RIFF"&&new TextDecoder().decode(bytes.slice(8,12))==="WEBP"){type="image/webp";ext="webp";}if(!type)throw new AppError("The file content is not a supported image. SVG and active content are not accepted.");
 const [db,env]=await Promise.all([getDB(),getEnv()]);if(!env.MEDIA)throw new AppError("Media storage is not configured.",503);const id=crypto.randomUUID(),key=`owned/${id}.${ext}`,time=now();await env.MEDIA.put(key,bytes,{httpMetadata:{contentType:type}});
 try{await db.prepare("INSERT INTO media_assets(id,key,filename,content_type,size,alt,credit,license,created_by,created_at) VALUES(?,?,?,?,?,?,?,?,?,?)").bind(id,key,file.name.slice(0,200),type,file.size,alt,credit,license,user.id,time).run();}catch(error){await env.MEDIA.delete(key);throw error;}await audit(user.id,"media.upload",id);return mapMedia((await db.prepare("SELECT * FROM media_assets WHERE id=?").bind(id).first<Record<string,unknown>>())!);
}
async function requireAsset(id:string,user:User){requireRole(user,WRITER_ROLES);const db=await getDB(),row=await db.prepare("SELECT * FROM media_assets WHERE id=?").bind(id).first<Record<string,unknown>>();if(!row)throw new AppError("Media not found.",404);if(user.role==="AUTHOR"&&row.created_by!==user.id)throw new AppError("This media belongs to another author.",403);return row;}
async function used(id:string){const db=await getDB();return !!await db.prepare("SELECT c.id FROM content_records c JOIN revisions r ON r.id IN(c.live_revision_id,c.draft_revision_id),json_tree(r.data) t WHERE t.type='text' AND t.value=? LIMIT 1").bind(`/api/media/${id}`).first();}
export async function updateMedia(id:string,value:Record<string,unknown>,user:User){const row=await requireAsset(id,user);const schema=z.object({alt:z.string().min(1).max(500),credit:z.string().max(500),license:z.string().min(1).max(500),visibility:z.enum(["PRIVATE","PUBLIC"])});const data=schema.parse({...row,...value});if(data.visibility!==row.visibility){requireRole(user,EDITOR_ROLES);if(data.visibility==="PRIVATE"&&await used(id))throw new AppError("This image is referenced by content. Replace those references before making it private.",409);}const db=await getDB();await db.prepare("UPDATE media_assets SET alt=?,credit=?,license=?,visibility=? WHERE id=?").bind(data.alt,data.credit,data.license,data.visibility,id).run();await audit(user.id,"media.update",id);return mapMedia({...row,...data});}
export async function deleteMedia(id:string,user:User){const row=await requireAsset(id,user);if(await used(id))throw new AppError("This image is still used by content. Replace it before deleting.",409);const [db,env]=await Promise.all([getDB(),getEnv()]);await env.MEDIA.delete(String(row.key));await db.prepare("DELETE FROM media_assets WHERE id=?").bind(id).run();await audit(user.id,"media.delete",id);}
