import Link from "next/link";
import { ArrowUpRight, BookOpen, CheckCheck, FileSearch, ListChecks, ShieldCheck } from "lucide-react";
import { getPublicContentByPath, getSettings, listCategories, listPublicContent } from "@/lib/server/content";
import { pageMetadata } from "@/lib/seo";
import { HeroIllustration } from "@/components/public/illustrations";
import { ArticleCards, CategoryCards, EmptyState, SectionHeader } from "@/components/public/ui";
import s from "@/components/public/public.module.css";

export async function generateMetadata() {const settings=await getSettings();return pageMetadata(`${settings.brandName} — Power accessories, thoughtfully chosen`,settings.siteDescription,"/");}

export default async function HomePage() {
  const [settings,categories,buyingGuides,recent,featured,methodology]=await Promise.all([getSettings(),listCategories(),listPublicContent({type:"BUYING_GUIDE",pageSize:3}),listPublicContent({pageSize:3}),listPublicContent({featured:true,pageSize:3}),getPublicContentByPath("/how-we-review")]);
  return <><section className={s.hero}><div className={`${s.wrap} ${s.heroInner}`}><div><div className={s.eyebrow}>The everyday power edit</div><h1>{settings.tagline === "A better connection. A smarter setup." ? <>A better connection.<br/><em>A smarter setup.</em></> : settings.tagline}</h1><p>{settings.siteDescription}</p><div className={s.actions}><Link href="/buying-guides" className={s.button}>Explore buying guides<ArrowUpRight size={16}/></Link><Link href="/categories" className={s.textLink}>Find your category<span aria-hidden="true">→</span></Link></div></div><div className={s.heroArt}><HeroIllustration/><span className={s.heroCaption}>Make room for a better setup.</span></div></div></section><div className={s.trustBar}><div className={`${s.wrap} ${s.trustInner}`}><span className={s.trustItem}><FileSearch/>Research with context</span><span className={s.trustItem}><ListChecks/>Comparisons that make sense</span><span className={s.trustItem}><ShieldCheck/>Clear affiliate disclosure</span></div></div><div className={s.wrap}>{settings.homeSections.filter(section=>section.visible).map(section=>{
    if(section.id==="categories")return <section key={section.id} className={s.section}><SectionHeader kicker="Start with the essentials" title={section.title} description="Small upgrades. A more considered space." href="/categories" linkText="All categories"/>{categories.length?<CategoryCards categories={categories}/>:<EmptyState title="A place for every setup." description="Our topic collection is being prepared. Check back for categories that help you explore your power essentials."/>}</section>;
    if(section.id==="buying-guides")return <section key={section.id} className={s.section}><SectionHeader kicker="Make an informed choice" title={section.title} description="The details that matter, brought into focus." href="/buying-guides" linkText="All buying guides"/>{buyingGuides.items.length?<ArticleCards articles={buyingGuides.items} categories={categories}/>:<EmptyState/>}</section>;
    if(section.id==="latest"){const articles=featured.items.length?featured.items:recent.items;return articles.length?<section key={section.id} className={s.section}><SectionHeader kicker={featured.items.length?"The editorial selection":"The latest reading"} title={section.title} href="/blog" linkText="All articles"/><ArticleCards articles={articles} categories={categories}/></section>:null;}
    if(section.id==="methodology")return <section key={section.id} className={s.methodology}><div><p className={s.kicker}>A little more clarity</p><h2>{section.title}</h2><p>Choosing a power accessory starts with understanding your setup. We make room for the useful details: intended use, documented specifications, and the tradeoffs behind a recommendation.</p>{methodology&&<Link href="/how-we-review" className={s.textLink}>How we review<ArrowUpRight size={16}/></Link>}</div><div className={s.methodologyItems}><div className={s.methodologyItem}><FileSearch/><div><h3>Evidence comes first</h3><p>Look for the sources and research basis alongside each published recommendation.</p></div></div><div className={s.methodologyItem}><CheckCheck/><div><h3>The whole picture</h3><p>Strengths, limitations, and the setups a product makes sense for.</p></div></div><div className={s.methodologyItem}><BookOpen/><div><h3>Useful, everyday context</h3><p>Clear explanations to help you ask better questions before you choose.</p></div></div></div></section>;
    return null;
  })}</div></>;
}

