import {z} from "zod";
import {getDB} from "@/lib/server/db";
import {getSettings,getPublicProduct,getPublicContentByPath} from "@/lib/server/content";
import {assertSameOrigin} from "@/lib/server/auth";
import {apiError,body,json,rateLimit} from "@/lib/server/http";
import {AppError,now} from "@/lib/server/editorial";
import {collectDocumentRefs,amazonDestination} from "@/lib/content";
export async function POST(request:Request){try{await assertSameOrigin(request);const settings=await getSettings();if(!settings.analyticsEnabled||!/(?:^|;\s*)ppp_consent=accepted(?:;|$)/.test(request.headers.get("cookie")??""))return new Response(null,{status:204});await rateLimit(request,"events",120,60);const data=z.object({id:z.uuid(),eventType:z.enum(["page_view","affiliate_click"]),path:z.string().max(500).regex(/^\/(?!\/)[^?#]*$/),articleId:z.string().max(100).optional(),productId:z.string().max(100).optional(),placement:z.string().max(100).optional()}).parse(await body(request,3000));if(/^\/(admin|api|preview)(\/|$)/.test(data.path))throw new AppError("This path is not public.");const article=await getPublicContentByPath(data.path);if(data.articleId&&article?.id!==data.articleId)throw new AppError("Invalid article reference.");if(data.eventType==="affiliate_click"){if(!data.productId)throw new AppError("A product is required.");const product=await getPublicProduct(data.productId);if(!product||!amazonDestination(product.data,settings.affiliateTag))throw new AppError("Invalid product destination.");if(article&&![...article.data.productIds,...collectDocumentRefs(article.data.document).products].includes(data.productId))throw new AppError("The product is not referenced by this article.");}
const db=await getDB();await db.prepare("INSERT OR IGNORE INTO analytics_events(id,event_type,article_id,product_id,path,placement,created_at) VALUES(?,?,?,?,?,?,?)").bind(data.id,data.eventType,article?.id??null,data.productId??null,data.path,data.placement??"",now()).run();return json({ok:true});}catch(error){return apiError(error);}}
